language: rust
sudo: false
rust: nightly

matrix:
  fast_finish: true
  include:
    - env: TARGET=i586-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu-emulated
    - env: TARGET=x86_64-linux-android
    - env: TARGET=arm-unknown-linux-gnueabihf
    - env: TARGET=arm-linux-androideabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=aarch64-linux-android
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=s390x-unknown-linux-gnu
    - env: TARGET=wasm32-unknown-unknown
    - os: osx
      env: TARGET=i686-apple-darwin
      script: ci/run.sh
    - os: osx
      env: TARGET=x86_64-apple-darwin NO_ADD=1
      script: ci/run.sh
    - env: DOCUMENTATION
      install: true
      script: ci/dox.sh
    - env: RUSTFMT=On TARGET=x86_64-unknown-linux-gnu
      before_script:
      - rustup component add rustfmt-preview
      script:
      - cargo fmt --all -- --check
    - env: CLIPPY=On TARGET=x86_64-unknown-linux-gnu
      before_script:
      - cargo install clippy
      script:
      - cargo clippy --all -- -D clippy-pedantic
  allow_failures:
    - env: CLIPPY=On TARGET=x86_64-unknown-linux-gnu

install:
  - rustup target add $TARGET || true

script:
  - cargo generate-lockfile
  - ci/run-docker.sh $TARGET $FEATURES

notifications:
  email:
    on_success: never
env:
  global:
    secure: i5Am1bhaK+6Zw/7b6uBxCPW+TYsPQ1EHaL8FMp0+KBeGtvpOIT1HsZd31C2gdvWouOVB/vjhS5qWa9YtkUw47Z7skiVRXdJfO+8ZUbH3ac8MUDc2uMrIRtEn37ncdn6IdsedD0MfqJc5BmGu9DUztHQ2oMokzEXGJINOdbadrZv8XUKNx+nlXOFXq6wQln8XhjBIFCP/JTkOr8zeuQdSH/TpaYMxsgfxwy4TSSQFRUmgUOevegcbjakeWvfd6pPiis0h275Ppykm9Jjkf7/RxL6C6uVgOZKcO7qVT/22PbrJwl5kucYelZr+gWXnxh65wyLXIy+t//6B1/3dhwuyr6U/LlxesvB8ZnS8Bt0cA4Loxh6yX/TTYTg734O56hjXRU6rlJW6RaaO6Vukv2s8kU+LhCSWijMtwRf7c2H0K1tksBT9wRZQZ06QxnR7P7jN48/QqAp1QZdT7jhXvOr8s7ROsJhbku0scUAOoNfTZ47SHjbMxGc7klI31BhaxFeaNsWAZMyIeigebhJ8gnZcPDO78J/6svBb83AgMLRPaO4l9y1png4iLdtXtkxr0S8F8pAf9VnDVSJBH6SN9/d7dRa1QwpNDpVcW52GEY5OQkVJ1Xkp9xbnW5nJpOXQIeJeix8VwsUXX289MUyPfOxDQhRCzeSExqks7P1veL+TNss=
