name: docs

on:
  push:
    branches:
      - master
      - port-ci-to-github-actions # during testing

jobs:
  docs:
    uses: ./.github/workflows/run-ci-script.yml
    with:
      setup_script: cargo install mdbook
      script: ci/dox.sh
